version: '3.9'

services:

  mariadb:
    build:
      context: ./mariadb
    container_name: docker-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mariadb/var/lib/mysql:/var/lib/mysql
    env_file:
      - ./.env

  webapp:
    depends_on:
      - mariadb
    build:
      context: ./
    container_name: docker-uasmash-webapp
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./bin:/server/bin
      - ./modules:/server/modules
      - ./public:/server/public
      - ./routes:/server/routes
      - ./views:/server/views
      - ./uploads:/server/uploads
    env_file:
      - ./.env
