version: '3.9'

services:

  mariadb:
    build:
      context: ./mariadb
    container_name: docker-mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"

  webapp:
    depends_on:
      - mariadb
    build:
      context: ./
    ports:
      - '3000:3000'
    container_name: docker-uasmash-webapp
    restart: always
    environment:
      NODE_ENV: "production"
